name: release zc folder encryption kit

on:
  workflow_dispatch:
    # This allows manual triggering of the workflow

permissions:
  contents: write  # Needed for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for the attestations step
      contents: write # Needed for creating releases
      attestations: write # Needed for creating attestations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          cd go/encrypt
          VERSION=$(grep "const tool_version" main.go | cut -d'"' -f2)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version extracted: ${VERSION}"
          cd ../..

      - name: Check if release already exists
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG_VERSION="v${VERSION}"
          
          echo "Checking if tag $TAG_VERSION already exists..."
          
          # Use the GitHub CLI to check if the release exists
          if gh release view "$TAG_VERSION" &> /dev/null; then
            echo "Release $TAG_VERSION already exists. Exiting workflow successfully."
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Release $TAG_VERSION does not exist. Continuing with build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'  # Ensure we're using a compatible version

      - name: Build zip and push release
        id: create_artifact
        if: steps.check_release.outputs.exists != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd go/encrypt
          make kit
          cd emergency-kit
          VERSION="${{ steps.get_version.outputs.version }}"
          ARTIFACT_NAME="zc-${VERSION}.zip"
          zip -r "../../../${ARTIFACT_NAME}" ./*
          cd ../../..
          echo "Created ZIP archive: ${ARTIFACT_NAME}"

          # Create release notes
          cat > release_notes.md << EOF
          This is a pre-built emergency-kit based on zc, a self-contained tool for encrypting folders and files.
          For full instructions, see the README.md file included in the package.
          EOF
          
          ls -la

          # Create the release with GitHub CLI
          TAG_VERSION="v${VERSION}"
          gh release create "$TAG_VERSION" \
            --title "zc folder encryption kit $TAG_VERSION" \
            --notes-file release_notes.md \
            "${ARTIFACT_NAME}"
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
            
      - name: Attest
        id: attest
        uses: actions/attest@v2
        with:
          subject-path: '${{ steps.create_artifact.outputs.artifact_name }}'
          predicate-type: 'https://slsa.dev/provenance/v1'
          output-path: 'attestation.json'
          attest-type: 'https://slsa.dev/provenance/v1'
          
      - name: Upload Attestation to release
        if: steps.check_release.outputs.exists != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG_VERSION="v${VERSION}"
          
          # Create attestation files for the release
          cp attestation.json "zc-${VERSION}.attestation.json"
          cp provenance.json "zc-${VERSION}.provenance.json"
          
          # Create a human-readable summary
          echo "ZC Folder Encryption Kit v${VERSION} - Build Attestation" > "zc-${VERSION}.attestation-summary.txt"
          echo "========================================================" >> "zc-${VERSION}.attestation-summary.txt"
          echo "Created: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> "zc-${VERSION}.attestation-summary.txt"
          echo "Build ID: ${{ github.run_id }}" >> "zc-${VERSION}.attestation-summary.txt"
          echo "Workflow: ${{ github.workflow }}" >> "zc-${VERSION}.attestation-summary.txt"
          echo "Repository: ${{ github.repository }}" >> "zc-${VERSION}.attestation-summary.txt"
          echo "Commit: ${{ github.sha }}" >> "zc-${VERSION}.attestation-summary.txt"
          echo "" >> "zc-${VERSION}.attestation-summary.txt"
          echo "This attestation provides cryptographic verification that the release" >> "zc-${VERSION}.attestation-summary.txt"
          echo "artifact was built from the specified source code in a secure and" >> "zc-${VERSION}.attestation-summary.txt"
          echo "reproducible manner." >> "zc-${VERSION}.attestation-summary.txt"
          
          # Create SHA256 checksum for the artifact
          ARTIFACT_NAME="${{ steps.create_artifact.outputs.artifact_name }}"
          sha256sum "$ARTIFACT_NAME" > "$ARTIFACT_NAME.sha256"
          
          # Upload attestation files to the release
          echo "Uploading attestation files to release ${TAG_VERSION}..."
          
          # Verify the release exists before uploading
          if gh release view "$TAG_VERSION" &> /dev/null; then
            gh release upload "$TAG_VERSION" "zc-${VERSION}.attestation.json" --clobber
            gh release upload "$TAG_VERSION" "zc-${VERSION}.provenance.json" --clobber
            gh release upload "$TAG_VERSION" "zc-${VERSION}.attestation-summary.txt" --clobber
            gh release upload "$TAG_VERSION" "$ARTIFACT_NAME.sha256" --clobber
            echo "Successfully uploaded attestation files to release ${TAG_VERSION}"
          else
            echo "Error: Release ${TAG_VERSION} not found. Cannot upload attestation files."
            exit 1
          fi
